Replace existing rules with new ones
smartprocure/eslint-config-smartprocure pull request #25
Opened 2017-08-24 16:13 UTC by sean-clayton

I'm not sure why, but Travis keeps running and I can't remove this repo from travis.org 🤷‍♂️ 

Also, anyone know how to remove codacy?

Closes #24

2017-08-24 18:59 UTC, sean-clayton commented
@smartprocure/development Here's the implementation of my proposed rules. Please let me know if you have any concerns since this will affect all of us eventually.

2017-08-24 20:02 UTC, daedalus28 requested changes

2017-08-24 20:02 UTC, daedalus28 commented on index.js
> +  'prefer-spread': 'warn',
this should be `error`

2017-08-25 18:47 UTC, daedalus28 approved these changes

2017-08-25 18:47 UTC, merged